services:
  app:
    build:
      context: .
      args:
        APP_ENV: ${NODE_ENV}
        NODE_ENV: ${NODE_ENV}
        PORT: ${PORT}
    command: ['pnpm', 'start:dev']
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      POSTGRES_URI: postgres://postgres:yourpassword@postgres:5432/smartlytics_db
      REDIS_URI: redis://redis:6379
      EVOLUTION_API_URL: http://evolution-api:8080
      BACKEND_DOMAIN: http://app:${PORT}
    volumes:
      - .:/home/node/app
      # ** Descomente se precisar persistir o node_modules:
      # - ./node_modules:/home/node/app/node_modules
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
      - redis
    networks:
      - smartlytics_network

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: smartlytics_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/init-db:/docker-entrypoint-initdb.d/
    networks:
      - smartlytics_network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - smartlytics_network

  evolution-api:
    image: atendai/evolution-api:homolog
    command: ["node", "./dist/main.js"]
    restart: always
    environment:
      LOG_LEVEL: ERROR,WARN,DEBUG,INFO,LOG,DARK
      LOG_COLOR: true
      LOG_BAILEYS: error
      AUTHENTICATION_API_KEY: YOUR_SUPER_SECURE_AUTHENTICATION_KEY
      AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES: true
      DEL_INSTANCE: 5
      DEL_TEMP_INSTANCES: true
      DATABASE_ENABLED: true
      DATABASE_PROVIDER: postgresql
      DATABASE_CONNECTION_URI: postgresql://postgres:yourpassword@postgres:5432/evolution_db?schema=public
      DATABASE_CONNECTION_CLIENT_NAME: evolution_docker
      DATABASE_SAVE_DATA_INSTANCE: true
      DATABASE_SAVE_DATA_NEW_MESSAGE: true
      DATABASE_SAVE_MESSAGE_UPDATE: true
      DATABASE_SAVE_DATA_CONTACTS: true
      DATABASE_SAVE_DATA_CHATS: true
      DATABASE_SAVE_DATA_LABELS: true
      DATABASE_SAVE_DATA_HISTORIC: true
      CONFIG_SESSION_PHONE_CLIENT: ${APP_NAME}
      CONFIG_SESSION_PHONE_NAME: Edge
      QRCODE_LIMIT: 30
      CACHE_REDIS_ENABLED: true
      CACHE_REDIS_URI: redis://redis:6379
      CACHE_REDIS_PREFIX_KEY: evolution
    ports:
      - '8080:8080'
    networks:
      - smartlytics_network

volumes:
  redis-data:
  postgres-data:

networks:
  smartlytics_network:
    driver: bridge
